# Generated by Django 5.2.7 on 2026-03-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedompost',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
    ]
